### ISSUE TITLE
Error: , Remote I/O error

### ISSUE THREAD

**Issue by marcosdepo** [fivdi/bme280#3]
Hi, when I run the first sample code, I got this error:

`[Error: , Remote I/O error] {
errno: 121,
code: '',
syscall: 'readByte'
} `

Code:
`const bme280 = require('bme280');
bme280.open().then(async sensor => {
  console.log(await sensor.read());
  await sensor.close();
}).catch(console.log);`

Hardware: Raspberry Pi 4
Sensor BME280

**Comment by fivdi** [comment]
What's the output of the command
```console
i2cdetect -y -r 1
```

**Comment by marcosdepo** [comment]
Here the response:

pi@raspberrypi:~ $ i2cdetect -y -r 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- 76 --

**Comment by fivdi** [comment]
Please read the documentation for the [open([options])](https://github.com/fivdi/bme280#openoptions) method. The default `i2cAddress` is 0x77 but on your system the i2cAddress is 0x76. Give the following a try and report your findings:
```js
const bme280 = require('bme280');

bme280.open({i2cAddress: 0x76}).then(async sensor => {
  console.log(await sensor.read());
  await sensor.close();
}).catch(console.log);
```

**Comment by marcosdepo** [comment]
Thanks a lot, it worked!
