### ISSUE TITLE
Remote I/O error] errno: 121 when running example code.

### ISSUE THREAD

**Issue by simonleventeattila** [fivdi/bme280#4]
Hi!

While trying to use bme280 module to get readings from a bme280 sensor I get the following error on a raspberry pi model b (2011 version) using node 10.9.0 (also tried  11.9.0): 

`{ [Error: , Remote I/O error] errno: 121, code: '', syscall: 'readByte' }`

Using a python script I am able to read the sensor data without issue. 

Is my hardware just too old or am I doing something wrong?

Thanks!

**Comment by fivdi** [comment]
What is the I2C address of your BME280?

**Comment by simonleventeattila** [comment]
Running `i2cdetect -y 1` returns:
`
![image](https://user-images.githubusercontent.com/17630649/102701563-e323cd00-4260-11eb-8fff-8e2fd03fed0a.png)

So the address is the usual 0x76.

**Comment by fivdi** [comment]
Please take a few moments to read the documentation for the open method. It explains what to do.

**Comment by simonleventeattila** [comment]
Yep, solved it. Leaving the "solution" here in case someone else skimps the documentation and gets here:
`i2cAddress: 0x76,`
So make sure you change the i2cAddress to the one your i2c sensor is using.
Thanks again for this package.

**Comment by fivdi** [comment]
Duplicate of #3
